# Generated by Django 4.0.4 on 2022-05-18 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExcelData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField(auto_created=True)),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('hobby', models.CharField(max_length=100)),
            ],
        ),
    ]
