# Generated by Django 4.0.4 on 2022-05-18 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exceldata',
            name='date_created',
            field=models.DateField(auto_created=True, null=True),
        ),
    ]
