# Generated by Django 4.0.4 on 2022-05-18 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload_app', '0002_alter_exceldata_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exceldata',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exceldata',
            name='date_created',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exceldata',
            name='hobby',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='exceldata',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
